### ISSUE TITLE
FileNotFound ~/HemTools/share/script/tabulatereadsAtoI-stranded.py 

### ISSUE THREAD

**Issue by Liozhang** [YichaoOU/HbF_BE_NG_2023#1]
Hello, I am a bioinformatics engineer and I am trying to reproduce the analysis workflow based on the method described in the article. I noticed that the provided workflow includes a file ~/HemTools/share/script/tabulatereadsAtoI-stranded.py, but I couldn't find this file in the repository https://github.com/YichaoOU/HemTools/tree/master/share/script. Could you please let me know if I am missing something?
Thanks !

**Comment by YichaoOU** [comment]
Sorry about that. The file is uploaded. 

Best,
Yichao

**Comment by Liozhang** [comment]
I really appreciate your effort in updating the code files. It has been incredibly helpful for me to reproduce the analysis process described in the article. 
Thank you so much!
